// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvKGj0CVbiFmycTiOVaS5ZJs69O9eNkSg',
    appId: '1:848064092897:web:83c23f5127381e6f9ff5a0',
    messagingSenderId: '848064092897',
    projectId: 'dtabot-d19c9',
    authDomain: 'dtabot-d19c9.firebaseapp.com',
    storageBucket: 'dtabot-d19c9.appspot.com',
    measurementId: 'G-WR42JV1G3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1c6Ix368huWYErBW_27zS_k8dA0qg6k',
    appId: '1:848064092897:android:1c285a23a162a8769ff5a0',
    messagingSenderId: '848064092897',
    projectId: 'dtabot-d19c9',
    storageBucket: 'dtabot-d19c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU6CjmMU0oBnXC5EHUIrl2Ryl56Qa814o',
    appId: '1:848064092897:ios:96ab7e276704842e9ff5a0',
    messagingSenderId: '848064092897',
    projectId: 'dtabot-d19c9',
    storageBucket: 'dtabot-d19c9.appspot.com',
    iosClientId:
        '848064092897-ts8q958o76ite5ps7mi19sroo4gri9ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.captone2DtaBot',
  );
}
